"$PYTHON_ENV"/bin/python ./src/ds_linked_list.py
# "$PYTHON_ENV"/bin/python ./src/ds_stack.py
# "$PYTHON_ENV"/bin/python ./src/ds_queue.py
# "$PYTHON_ENV"/bin/python ./src/ds_deque.py
# "$PYTHON_ENV"/bin/python ./src/ds_graph.py
# "$PYTHON_ENV"/bin/python ./src/ds_knight_tour_problem.py
# "$PYTHON_ENV"/bin/python ./src/ds_breadth_first_search.py
# "$PYTHON_ENV"/bin/python ./src/ds_depth_first_search.py
# "$PYTHON_ENV"/bin/python ./src/ds_topological_sort.py
# "$PYTHON_ENV"/bin/python ./src/ds_priority_queue.py
# "$PYTHON_ENV"/bin/python ./src/ds_dijkstra_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/ds_prim_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/kahn_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/bellman-ford_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/floyd-warshall_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/smol_graph.py
# "$PYTHON_ENV"/bin/python ./src/edmonds-karp_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/bfs.py
# "$PYTHON_ENV"/bin/python ./src/dfs.py
# "$PYTHON_ENV"/bin/python ./src/dijkstra_algorithm.py
# "$PYTHON_ENV"/bin/python ./src/prim_algorithm.py
